version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: nutrismart_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nutrition_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nutri-network

  backend-app:
    build: .
    container_name: nutrismart_backend
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/nutrition_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "8080:8080"
    networks:
      - nutri-network

volumes:
  postgres_data:

networks:
  nutri-network:
    driver: bridge